import os
import logging
import random

# Maps NWS event type strings (lowercase) to audio_playlist/alerts/ subfolder names.
# Priority-1 events get their own folder for immediate interrupt handling.
ALERT_FOLDER_MAP = {
    # Tornado
    "tornado emergency":            "priority_1",
    "tornado warning":              "tornado",
    "tornado watch":                "tornado",
    # Thunderstorm
    "severe thunderstorm warning":  "thunderstorm",
    "severe thunderstorm watch":    "thunderstorm",
    # Flooding
    "flash flood emergency":        "priority_1",
    "flash flood warning":          "flooding",
    "flash flood watch":            "flooding",
    "flood warning":                "flooding",
    "flood watch":                  "flooding",
    "flood advisory":               "flooding",
    "coastal flood warning":        "flooding",
    "coastal flood watch":          "flooding",
    "coastal flood advisory":       "flooding",
    # Hurricane / Tropical
    "hurricane warning":            "hurricane",
    "hurricane watch":              "hurricane",
    "tropical storm warning":       "hurricane",
    "tropical storm watch":         "hurricane",
    "storm surge warning":          "hurricane",
    "storm surge watch":            "hurricane",
    "hurricane local statement":    "hurricane",
    "extreme wind warning":         "hurricane",
    "hurricane force wind warning": "hurricane",
    "hurricane force wind watch":   "hurricane",
    # Fog
    "dense fog advisory":           "fog",
    "freezing fog advisory":        "fog",
    "dense smoke advisory":         "fog",
    # Fire
    "red flag warning":             "fire",
    "fire weather watch":           "fire",
    "extreme fire danger":          "fire",
    # Freeze / Winter
    "freeze warning":               "freeze",
    "freeze watch":                 "freeze",
    "frost advisory":               "freeze",
    "hard freeze warning":          "freeze",
    "winter storm warning":         "freeze",
    "winter storm watch":           "freeze",
    "winter weather advisory":      "freeze",
    "ice storm warning":            "freeze",
    "blizzard warning":             "freeze",
    "cold weather advisory":        "freeze",
}

# Root of the broadcast-facing audio library
ALERT_AUDIO_ROOT = "/home/lh_admin/weather_station/audio/alerts"

# Shared audio playlist library (all non-alert content)
PLAYLIST_ROOT = "/home/lh_admin/audio_playlist"

# Subfolders checked in priority order for playback
ALERT_PRIORITY_ORDER = [
    "priority_1", "tornado", "thunderstorm", "hurricane",
    "flooding", "fire", "freeze", "fog", "other_alerts",
]

# Zone audio root and shared top-of-hour
ZONES_ROOT = "/home/lh_admin/weather_station/audio/zones"
SHARED_TOP_OF_HOUR = os.path.join(ZONES_ROOT, "_shared", "top_of_hour")


def _collect_wavs(root: str) -> list:
    """
    Walk *root* recursively and return all WAV paths (excluding _processed files).
    Returns an empty list if root does not exist.
    """
    result = []
    if not os.path.isdir(root):
        return result
    for dirpath, _dirs, files in os.walk(root):
        for f in files:
            if f.lower().endswith(".wav") and "_processed" not in f:
                result.append(os.path.join(dirpath, f))
    return result


class FileRouter:
    def __init__(self, settings):
        self.logger = logging.getLogger("FileRouter")
        self.settings = settings
        self._traffic_idx: int = 0   # cycles through 01.wav → 02.wav → … in order

        audio = settings.AUDIO_PATH
        self.audio_dirs = {
            # Station audio library (files live here)
            "top_of_hour":         os.path.join(audio, "top_of_hour"),
            "educational":         os.path.join(audio, "educational"),
            "imaging":             os.path.join(audio, "imaging"),
            "alerts":              os.path.join(audio, "alerts"),
            "traffic":             os.path.join(audio, "traffic"),
            "weather":             os.path.join(ZONES_ROOT, "all_florida", "weather"),
            "generated_wav_files": os.path.join(audio, "generated_wav_files"),
            # Airport weather WAVs (generated by airport_weather_tts service)
            "airport_weather":     os.path.join(ZONES_ROOT, "all_florida", "airport_weather"),
            # Priority alerts (severe/extreme) — skipped silently when empty
            "priority_1":          os.path.join(ZONES_ROOT, "all_florida", "priority_1"),
            # Shared broadcast library (populated separately)
            "pl_top_of_hour":         os.path.join(PLAYLIST_ROOT, "top_of_the_hour"),
            "pl_educational":         os.path.join(PLAYLIST_ROOT, "educational"),
            "pl_imaging":             os.path.join(PLAYLIST_ROOT, "imaging"),
            "pl_traffic":             os.path.join(PLAYLIST_ROOT, "traffic"),
            "pl_weather":             os.path.join(PLAYLIST_ROOT, "weather"),
            "pl_generated_wav_files": os.path.join(PLAYLIST_ROOT, "generated_wav_files"),
        }
        self.logger.info("FileRouter initialized")

    def route_alert_by_event(self, event_type: str) -> str:
        """
        Map a NWS event type string to the correct audio_playlist/alerts/ subfolder.
        Returns the full directory path, creating it if needed.
        """
        subfolder = ALERT_FOLDER_MAP.get(event_type.lower().strip(), "other_alerts")
        path = os.path.join(ALERT_AUDIO_ROOT, subfolder)
        os.makedirs(path, exist_ok=True)
        self.logger.debug(f"Routing '{event_type}' → {path}")
        return path

    def get_next_alert_file(self) -> str | None:
        """
        Return the oldest pending alert WAV across all subfolders, checking
        higher-priority subfolders first (priority_1 → tornado → … → other_alerts).
        Returns None when no alert WAVs are waiting.
        """
        for subfolder in ALERT_PRIORITY_ORDER:
            folder = os.path.join(ALERT_AUDIO_ROOT, subfolder)
            if not os.path.isdir(folder):
                continue
            files = sorted(
                f for f in os.listdir(folder)
                if f.lower().endswith(".wav") and "_processed" not in f
            )
            if files:
                path = os.path.join(folder, files[0])
                self.logger.info(f"Next alert: {path}")
                return path
        return None

    # ------------------------------------------------------------------
    # Zone-aware helpers
    # ------------------------------------------------------------------

    def get_zone_mode_files(self, zone: str, mode: str) -> list:
        """Return sorted WAV list from zones/{zone}/current_mode/{mode}/."""
        folder = os.path.join(ZONES_ROOT, zone, "current_mode", mode)
        if not os.path.isdir(folder):
            return []
        return [
            os.path.join(folder, f)
            for f in sorted(os.listdir(folder))
            if f.lower().endswith(".wav") and "_processed" not in f
        ]

    def get_zone_profile_files(self, zone: str, subfolder: str) -> list:
        """
        Return WAV list from zones/{zone}/profile/{subfolder}/.
        For 'imaging', walks all subfolders (jingles, station_ids, sweepers, promos).
        For 'psa', returns only the top-level folder contents.
        """
        folder = os.path.join(ZONES_ROOT, zone, "profile", subfolder)
        if subfolder == "imaging":
            return _collect_wavs(folder)
        # psa — flat list only
        if not os.path.isdir(folder):
            return []
        return [
            os.path.join(folder, f)
            for f in os.listdir(folder)
            if f.lower().endswith(".wav") and "_processed" not in f
        ]

    def get_shared_top_of_hour_file(self) -> str | None:
        """Return a random WAV from the shared _shared/top_of_hour/ folder."""
        if not os.path.isdir(SHARED_TOP_OF_HOUR):
            return None
        files = [
            f for f in os.listdir(SHARED_TOP_OF_HOUR)
            if f.lower().endswith(".wav") and "_processed" not in f
        ]
        return os.path.join(SHARED_TOP_OF_HOUR, random.choice(files)) if files else None

    def get_zone_airport_weather_files(self, zone: str) -> list:
        """Return WAV list from zones/{zone}/airport_weather/."""
        folder = os.path.join(ZONES_ROOT, zone, "airport_weather")
        if not os.path.isdir(folder):
            return []
        return [
            os.path.join(folder, f)
            for f in os.listdir(folder)
            if f.lower().endswith(".wav") and "_processed" not in f
        ]

    def get_zone_alert_file(self, zone: str) -> str | None:
        """Return highest-priority pending alert WAV for a zone."""
        for subfolder in ALERT_PRIORITY_ORDER:
            folder = os.path.join(ZONES_ROOT, zone, subfolder)
            if not os.path.isdir(folder):
                continue
            files = sorted(
                f for f in os.listdir(folder)
                if f.lower().endswith(".wav") and "_processed" not in f
            )
            if files:
                path = os.path.join(folder, files[0])
                self.logger.info(f"[{zone}] next alert: {path}")
                return path
        return None

    # Categories that contain subfolders — walk recursively for these
    _RECURSIVE_CATEGORIES = {"imaging", "pl_imaging", "weather"}

    def get_next_file(self, category="educational"):
        folder = self.audio_dirs.get(category)
        if not folder or not os.path.isdir(folder):
            self.logger.warning(f"No folder for category '{category}'")
            return None

        if category in self._RECURSIVE_CATEGORIES:
            files = _collect_wavs(folder)
        else:
            files = [
                os.path.join(folder, f)
                for f in os.listdir(folder)
                if f.lower().endswith(".wav") and "_processed" not in f
            ]

        if not files:
            self.logger.warning(f"No WAV files in '{folder}'")
            return None

        if category == "traffic":
            # Play traffic clips in sorted order (01.wav → 02.wav → …) so that
            # the most-severe incident (lowest number) always plays first.
            files = sorted(files)
            self._traffic_idx = self._traffic_idx % len(files)
            next_file = files[self._traffic_idx]
            self._traffic_idx = (self._traffic_idx + 1) % len(files)
        else:
            next_file = random.choice(files)

        self.logger.info(f"Next file selected: {next_file}")
        return next_file
